name: Manually run tests on staging
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install dependancies
        uses: php-actions/composer@v5
        with:
          php_version: 7.3
      - name: PHPUnit tests
        uses: php-actions/phpunit@v2
        env:
          API_KEY: ${{ secrets.STAGING_API_KEY }}
          BASE_URI: https://sandbox-staging.api.video
        with:
          args: tests